require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

describe "/group_events" do
  # This should return the minimal set of attributes required to create a valid
  # GroupEvent. As you add validations to GroupEvent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
        name: 'Growth Hacking meeting',
        description: 'We will discuss about our growth hacking planning',
        location: 'Conference Room',
        starts: DateTime.strptime('2021-03-06T10:05:06+07:00', '%Y-%m-%dT%H:%M:%S%z'),
        ends: DateTime.strptime('2021-03-06T10:35:06+07:00', '%Y-%m-%dT%H:%M:%S%z'),
        status: 2
    }
  }

  let(:invalid_attributes) {
    {
        name: '',
        description: '',
        status: 2
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # GroupEventsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      GroupEvent.create! valid_attributes
      get group_events_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      group_event = GroupEvent.create! valid_attributes
      get group_events_url(group_event), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GroupEvent" do
        expect {
          post group_events_url,
               params: { group_event: valid_attributes }, headers: valid_headers, as: :json
        }.to change(GroupEvent, :count).by(1)
      end

      it "renders a JSON response with the new group_event" do
        post group_events_url,
             params: { group_event: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GroupEvent" do
        expect {
          post group_events_url,
               params: { group_event: invalid_attributes }, as: :json
        }.to change(GroupEvent, :count).by(0)
        expect(response.content_type).to match(a_string_including("application/json"))
      end

      it "renders a JSON response with errors for the new group_event" do
        post group_events_url,
             params: { group_event: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
            name: 'Growth Hacking Meeting | Planning for 2021'
        }
      }

      it "updates the requested group_event" do
        group_event = GroupEvent.create! valid_attributes
        patch group_event_path(group_event),
              params: { group_event: new_attributes }, headers: valid_headers, as: :json
        group_event.reload
        expect(group_event.name).to eql new_attributes[:name]
      end

      it "renders a JSON response with the group_event" do
        group_event = GroupEvent.create! valid_attributes
        patch group_event_path(group_event),
              params: { group_event: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the group_event" do
        group_event = GroupEvent.create! valid_attributes
        patch group_event_path(group_event),
              params: { group_event: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /" do
    it "destroys the requested group_event" do
      group_event = GroupEvent.create! valid_attributes
      expect {
        delete group_event_path(group_event), headers: valid_headers, as: :json
      }.to change(GroupEvent, :count).by(-1)
    end
  end
end
